name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev --skip-lock
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=pyoinformatics tests --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        # args: ". --check  -l 100   --verbose "
        args: "."
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
